// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANW6pJC3000aEEinfxSX4RwqOmtnwXJ3o',
    appId: '1:429108020551:web:819b1b979c07749dc97862',
    messagingSenderId: '429108020551',
    projectId: 'self-notif-try',
    authDomain: 'self-notif-try.firebaseapp.com',
    storageBucket: 'self-notif-try.appspot.com',
    measurementId: 'G-N8MWF0JP4F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj1aB8OnD1FCMpRuquaCaH_enXT8M31Xg',
    appId: '1:429108020551:android:cb4b3db1315861d4c97862',
    messagingSenderId: '429108020551',
    projectId: 'self-notif-try',
    storageBucket: 'self-notif-try.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKmqFmW6yAzeQRqFqu21LXxbGOTqz-IPo',
    appId: '1:429108020551:ios:cb194e3bc9c04c63c97862',
    messagingSenderId: '429108020551',
    projectId: 'self-notif-try',
    storageBucket: 'self-notif-try.appspot.com',
    iosClientId: '429108020551-h2vi3cuinod0srjmtmf4hirhohevl7r4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
